### ISSUE TITLE
Codicons not being patched properly

### ISSUE THREAD

**Issue by hsheikhali1** [mortepau/codicons.nvim#2]
So I tried to patch fonts with codicons many times but the fonts don't register correctly in alacrity :/ Any reason why?

**Comment by mortepau** [comment]
Did you install the font after generating the patched font? It might also be that you have to change the font setting in Alacritty so that it matches the name of the patched font.
As I'm not entirely sure what you mean by "register correctly" it is difficult to help you.

**Comment by hsheikhali1** [comment]
Tbh, I took the time to actually read your instructions and got them working properly now lol.

**Comment by mortepau** [comment]
That's awesome!
