### ISSUE TITLE
Codicon doesn't exist anymore?

### ISSUE THREAD

**Issue by LacueyDavid** [mortepau/codicons.nvim#3]
Hello

I just tried to download the Codicon using the link on the Dap Ui repository,
but it look like the Codicon.ttf doesn't exist anymore? So I can't get the font for the Ui.

thanks for reading.

**Comment by mortepau** [comment]
Seems like they moved the dist/codicon.ttf artifact to the build workflow: https://github.com/microsoft/vscode-codicons/commit/8d306bbf5e2f06d02c069d18bc37dd6738557295
For now, any of these runs seem to have the codicons.ttf artifact: https://github.com/microsoft/vscode-codicons/actions/workflows/build.yml?query=is%3Asuccess+branch%3Amain
